# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/simulator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/simulator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/simulator.proto\x12\x05proto\"\x8f\x02\n\x10\x41gentObservation\x12\x17\n\x0fis_channel_busy\x18\x01 \x01(\x02\x12\x18\n\x10has_data_to_send\x18\x02 \x01(\x02\x12\x1d\n\x15outbound_queue_length\x18\x03 \x01(\x02\x12%\n\x1dtop_message_wait_time_seconds\x18\x04 \x01(\x02\x12\x1e\n\x16\x63onsecutive_idle_steps\x18\x05 \x01(\x02\x12\"\n\x1alast_send_caused_collision\x18\x06 \x01(\x02\x12\"\n\x1asteps_since_last_collision\x18\x07 \x01(\x02\x12\x1a\n\x12\x63hannel_busy_ratio\x18\x08 \x01(\x02\"X\n\nAgentState\x12,\n\x0bobservation\x18\x01 \x01(\x0b\x32\x17.proto.AgentObservation\x12\x0e\n\x06reward\x18\x02 \x01(\x02\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\",\n\x0bStepRequest\x12\x1d\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\r.proto.Action\"0\n\x0cStepResponse\x12 \n\x05state\x18\x01 \x01(\x0b\x32\x11.proto.AgentState\"\x0e\n\x0cResetRequest\"1\n\rResetResponse\x12 \n\x05state\x18\x01 \x01(\x0b\x32\x11.proto.AgentState**\n\x06\x41\x63tion\x12\x0f\n\x0b\x41\x43TION_WAIT\x10\x00\x12\x0f\n\x0b\x41\x43TION_SEND\x10\x01\x32t\n\tSimulator\x12\x31\n\x04Step\x12\x12.proto.StepRequest\x1a\x13.proto.StepResponse\"\x00\x12\x34\n\x05Reset\x12\x13.proto.ResetRequest\x1a\x14.proto.ResetResponse\"\x00\x42\x15Z\x13\x41ir-Simulator/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.simulator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023Air-Simulator/proto'
  _globals['_ACTION']._serialized_start=559
  _globals['_ACTION']._serialized_end=601
  _globals['_AGENTOBSERVATION']._serialized_start=33
  _globals['_AGENTOBSERVATION']._serialized_end=304
  _globals['_AGENTSTATE']._serialized_start=306
  _globals['_AGENTSTATE']._serialized_end=394
  _globals['_STEPREQUEST']._serialized_start=396
  _globals['_STEPREQUEST']._serialized_end=440
  _globals['_STEPRESPONSE']._serialized_start=442
  _globals['_STEPRESPONSE']._serialized_end=490
  _globals['_RESETREQUEST']._serialized_start=492
  _globals['_RESETREQUEST']._serialized_end=506
  _globals['_RESETRESPONSE']._serialized_start=508
  _globals['_RESETRESPONSE']._serialized_end=557
  _globals['_SIMULATOR']._serialized_start=603
  _globals['_SIMULATOR']._serialized_end=719
# @@protoc_insertion_point(module_scope)
