# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: simulator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'simulator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsimulator.proto\x12\x05proto\"\xcc\x01\n\x10\x41gentObservation\x12\x13\n\x0bhas_message\x18\x01 \x01(\x08\x12-\n\x14top_message_priority\x18\x02 \x01(\x0e\x32\x0f.proto.Priority\x12\x1c\n\x14primary_channel_busy\x18\x03 \x01(\x08\x12\x1b\n\x13\x62\x61\x63kup_channel_busy\x18\x04 \x01(\x08\x12\x1a\n\x12pending_acks_count\x18\x05 \x01(\x05\x12\x1d\n\x15outbound_queue_length\x18\x06 \x01(\x05\"X\n\nAgentState\x12,\n\x0bobservation\x18\x01 \x01(\x0b\x32\x17.proto.AgentObservation\x12\x0e\n\x06reward\x18\x02 \x01(\x02\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\"~\n\x0bStepRequest\x12\x30\n\x07\x61\x63tions\x18\x01 \x03(\x0b\x32\x1f.proto.StepRequest.ActionsEntry\x1a=\n\x0c\x41\x63tionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1c\n\x05value\x18\x02 \x01(\x0e\x32\r.proto.Action:\x02\x38\x01\"\x81\x01\n\x0cStepResponse\x12/\n\x06states\x18\x01 \x03(\x0b\x32\x1f.proto.StepResponse.StatesEntry\x1a@\n\x0bStatesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.proto.AgentState:\x02\x38\x01\"\x0e\n\x0cResetRequest\"\x83\x01\n\rResetResponse\x12\x30\n\x06states\x18\x01 \x03(\x0b\x32 .proto.ResetResponse.StatesEntry\x1a@\n\x0bStatesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.proto.AgentState:\x02\x38\x01*b\n\x06\x41\x63tion\x12\x16\n\x12\x41\x43TION_UNSPECIFIED\x10\x00\x12\x0f\n\x0b\x41\x43TION_WAIT\x10\x01\x12\x17\n\x13\x41\x43TION_SEND_PRIMARY\x10\x02\x12\x16\n\x12\x41\x43TION_SEND_BACKUP\x10\x03*u\n\x08Priority\x12\x18\n\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n\x0cPRIORITY_LOW\x10\x01\x12\x13\n\x0fPRIORITY_MEDIUM\x10\x02\x12\x11\n\rPRIORITY_HIGH\x10\x03\x12\x15\n\x11PRIORITY_CRITICAL\x10\x04\x32t\n\tSimulator\x12\x31\n\x04Step\x12\x12.proto.StepRequest\x1a\x13.proto.StepResponse\"\x00\x12\x34\n\x05Reset\x12\x13.proto.ResetRequest\x1a\x14.proto.ResetResponse\"\x00\x42\x15Z\x13\x41ir-Simulator/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simulator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023Air-Simulator/proto'
  _globals['_STEPREQUEST_ACTIONSENTRY']._loaded_options = None
  _globals['_STEPREQUEST_ACTIONSENTRY']._serialized_options = b'8\001'
  _globals['_STEPRESPONSE_STATESENTRY']._loaded_options = None
  _globals['_STEPRESPONSE_STATESENTRY']._serialized_options = b'8\001'
  _globals['_RESETRESPONSE_STATESENTRY']._loaded_options = None
  _globals['_RESETRESPONSE_STATESENTRY']._serialized_options = b'8\001'
  _globals['_ACTION']._serialized_start=733
  _globals['_ACTION']._serialized_end=831
  _globals['_PRIORITY']._serialized_start=833
  _globals['_PRIORITY']._serialized_end=950
  _globals['_AGENTOBSERVATION']._serialized_start=27
  _globals['_AGENTOBSERVATION']._serialized_end=231
  _globals['_AGENTSTATE']._serialized_start=233
  _globals['_AGENTSTATE']._serialized_end=321
  _globals['_STEPREQUEST']._serialized_start=323
  _globals['_STEPREQUEST']._serialized_end=449
  _globals['_STEPREQUEST_ACTIONSENTRY']._serialized_start=388
  _globals['_STEPREQUEST_ACTIONSENTRY']._serialized_end=449
  _globals['_STEPRESPONSE']._serialized_start=452
  _globals['_STEPRESPONSE']._serialized_end=581
  _globals['_STEPRESPONSE_STATESENTRY']._serialized_start=517
  _globals['_STEPRESPONSE_STATESENTRY']._serialized_end=581
  _globals['_RESETREQUEST']._serialized_start=583
  _globals['_RESETREQUEST']._serialized_end=597
  _globals['_RESETRESPONSE']._serialized_start=600
  _globals['_RESETRESPONSE']._serialized_end=731
  _globals['_RESETRESPONSE_STATESENTRY']._serialized_start=517
  _globals['_RESETRESPONSE_STATESENTRY']._serialized_end=581
  _globals['_SIMULATOR']._serialized_start=952
  _globals['_SIMULATOR']._serialized_end=1068
# @@protoc_insertion_point(module_scope)
